print("Please enter five numbers.")
num_1 = float(input())
num_2 = float(input())
num_3 = float(input())
num_4 = float(input())
num_5 = float(input())
num_6 = (num_1 + num_2 + num_3 + num_4 + num_5)
print(num_6 / 5)